name: Upload to S3 and Notify Slack

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Enter the name of the file'
        required: true
        default: 'rand.txt'

jobs:
  echo-file-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload file to S3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ${{ github.event.inputs.filename }}
          destination: s3://gha-s3-eddy/
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1

      - name: Notify Slack on Job's Success
        if: ${{ success() }}
        uses: wearerequired/slack-messaging-action@v1
        with:
          bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: gha_interns
          payload: >
            {
              "username": "deployer",
              "text": "Job Successful\nFile URL: https://gha-s3-eddy.s3.us-east-1.amazonaws.com/${{ github.event.inputs.filename }}",
              "attachments": [
                {
                  "author_name": "${{ github.event.workflow_job.runner_name }}",
                  "fields": [
                    {
                      "title": "Link to S3 bucket",
                      "value": "<https://gha-s3-eddy.s3.us-east-1.amazonaws.com/${{ github.event.inputs.filename }}|File URL>",
                      "short": false
                    }
                  ],
                  "footer": "<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                }
              ]
            }
