name: Random numbers

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'File to display'
        required: true
        default: 'rand.txt'
    
jobs:
  echo_file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Display file contents
      id: echo_contents
      run: |
        content=$(cat ${{ github.event.inputs.filename }})
        echo "$content"

  notify_slack:
    runs-on: ubuntu-latest
    needs: [echo_file]
    if: always()
    steps:
    - name: Notify Slack on Job's Success
      if: success()
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: 'gha_interns'
        payload: >
          {
            "username": "Edmond & Jide",
            "text": "$content"
          }

  convert_to_json:
    runs-on: ubuntu-latest
    needs: [echo_file]
    if: always()
    steps:
    - name: Install jq
      run: sudo apt-get install jq
  
    - name: Display file contents and convert to JSON
      run: |
        echo "$content"
        json_output=$(echo "$content" | jq -Rs '{items: split("\n")[:-1] | to_entries | map({("item" + (.key + 1 | tostring)): .value}) | add}')
        echo "JSON Output: $json_output"

    - name: Notify Slack on Job's Success
      if: success()
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: 'gha_interns'
        payload: >
          {
            "username": "Edmond & Jide",
            "text": "$json_output"
          }