name: Process File and Notify Slack with Bot Token

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Enter the name of the file'
        required: true
        default: 'rand.txt'

jobs:
  process-file:
    runs-on: ubuntu-latest
    outputs:
      file-content: ${{ steps.readfile.outputs.content }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read and echo file content
        id: readfile
        run: |
          content=$(cat ${{ github.event.inputs.filename }})
          echo "::set-output name=content::$content"

  notify-slack:
    runs-on: ubuntu-latest
    needs: process-file
    if: always()
    steps:
      - name: Send notification to Slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
           # For posting a rich message using Block Kit
            payload: |
                {
                "text": "GitHub Action build result: ${{ job.status }}
                "blocks": [
                    {
                    "type": "section",
                    "text": "File processed: ${{ needs.process-file.outputs.file-content }}"
                    }
                ]
                }
        env:
         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
