name: Process User-Input File

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Enter the name of the file'
        required: true
        default: 'rand.txt'

jobs:
  process-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read and echo file content
        run: |
          filename=${{ github.event.inputs.filename }}
          content=$(cat $filename)
          echo "$content"
