name: Process File and Notify Slack with Bot Token

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Enter the name of the file'
        required: true
        default: 'rand.txt'

jobs:

  echo-file-content:
    runs-on: ubuntu-latest
    outputs:
      file-content: ${{ steps.echofile.outputs.content }}

    steps:
     - name: Checkout repository
       uses: actions/checkout@v2

     - name: Echo file content
       id: echofile
       run: |
            content=$(cat ${{ github.event.inputs.filename }})
            echo "::set-output name=content::$content"  

     - name: Notify Slack on Job's Success
       if: ${{ success() }}
       uses: wearerequired/slack-messaging-action@v1
       with:
                bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
                channel: gha_interns 
                payload: >-
                  {
                   
                    "username": "Deployer",
                    "text":"${{steps.echofile.outputs.content}}"
                  }
       

  process-file:
    runs-on: ubuntu-latest
    needs: echo-file-content
    outputs:
      file-content: ${{ steps.readfile.outputs.content }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read and echo file content
        id: readfile
        run: |
          content=$(awk '{print "\""$0"\""}' ${{ github.event.inputs.filename }} | paste -sd, -)
          echo "{\"item\":[$content]}" > codes.json
          echo "::set-output name=content::$(cat codes.json)"

      - name: Notify Slack on Job's Success
        if: ${{ success() }}
        uses: wearerequired/slack-messaging-action@v1
        with:
            bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
            channel: gha_interns 
            payload: >-
              {
               
                "username": "Deployer",
                "text":"${{ needs.process-file.outputs.file-content }}"
              }
