name: Random numbers

on: 
    workflow_dispatch:


jobs:
    echo_random_number:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Echo numbers
          run: cat rand.txt
     