name: Echo Random Numbers

on:
  workflow_dispatch:

jobs:
  read_numbers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Read file and store content in a variable
      id: read_file
      run: |
        content=$(cat rand.txt)
        echo "::set-output name=file_content::$content"

  notify_slack:
    runs-on: ubuntu-latest
    needs: [read_numbers]  # Wait for read_numbers job to complete
    if: always()  # Send notification even if read_numbers job fails
    steps:
    - name: Send content to Slack
      if: success()  # Send notification only if read_numbers job succeeds
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: your_slack_channel  # Replace with your Slack channel
        payload: >
          {
            "text": "Contents of numbers.txt: ${{ needs.read_numbers.outputs.file_content }}"
          }
