name: Random numbers

on: 
    workflow_dispatch:
        inputs:
            filename:
                description: 'File to display'
                required: true
                default: 'rand.txt'
    
jobs:
    display_file:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Display file contents
        run: cat ${{ github.event.inputs.filename }}