name: Process File and Notify Slack with Bot Token

on: 
    workflow_dispatch:
        inputs:
            filename:
              description: 'Enter the name of the file'
              required: true
              default: 'rand.txt'

jobs:
  echo-file-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo file content
        id: my_Letter
        run: |
          Letter=$(cat "${{ github.event.inputs.filename }}")
          echo "Letter<<EOF" >> $GITHUB_ENV
          echo "$Letter" >> $GITHUB_ENV
        #   echo "EOF" >> $GITHUB_ENV

      - name: Display string
        run: |
          echo "${{ env.Letter }}"

      - name: Notify Slack on Job's Success
        if: ${{ success() }}
        uses: wearerequired/slack-messaging-action@v1
        with:
          bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: gha_interns     
          payload: >-
            {
                "username": "deployer",
                "text": "edmond"
            }
            
