name: Random numbers

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'File to display'
        required: true
        default: 'rand.txt'
    
jobs:
  echo_file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Display file contents
      run: cat ${{ github.event.inputs.filename }}
      id: echo_contents
      continue-on-error: true  # Continue even if cat command fails

  notify_slack:
    runs-on: ubuntu-latest
    needs: [echo_file]
    if: always()  # Notify Slack even if previous steps fail
    steps:
    - name: Store the output in a variable
      run: |
        content=$(cat ${{ github.event.inputs.filename }})
        echo "::set-output name=output::$content"

    - name: Notify Slack on Job's Success
      if: success()  # Notify Slack only if previous steps succeed
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: githubactions 
        payload: >
          {
            "username": "Edmond & Jide",
            "text": "Contents of ${{ github.event.inputs.filename }}: ${{ needs.echo_file.outputs.output }}"
          }
