name: Random numbers

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'File to display'
        required: true
        default: 'rand.txt'
    
jobs:
  echo_file:
    runs-on: ubuntu-latest
    outputs:
      file_content: ${{ steps.echo_contents.outputs.content }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Display file contents
      id: echo_contents
      run: |
        content=$(cat ${{ github.event.inputs.filename }})
        echo "::set-output name=content::$content"

  notify_slack:
    runs-on: ubuntu-latest
    needs: echo_file
    if: always()
    steps:
    - name: Notify Slack on Job's Success
      if: success()
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: 'Gha_interns'
        payload: >
          {
            "username": "Edmond & Jide",
            "text": "Contents of ${{ github.event.inputs.filename }}: ${{ needs.echo_file.outputs.file_content }}"
          }

  convert_to_json:
    runs-on: ubuntu-latest
    needs: [echo_file]
    if: always()
    steps:
    - name: Install jq
      run: sudo apt-get install jq
  
    - name: Convert text file to JSON
      id: json_convert
      run: |
        content=$(cat ${{ github.event.inputs.filename }})
        json=$(echo "$content" | jq -Rn '{ items: [inputs | split("\n") | .[] | select(. != "")] }')
        echo "::set-output name=json_content::$json"

    
    - name: Notify Slack on Job's Success
      if: success()
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: 'Gha_interns'
        payload: >
          {
            "username": "Edmond & Jide",
            "text": "JSON content of ${{ github.event.inputs.filename }}:",
            "attachments": [
              {
                "text": "${{ steps.json_convert.outputs.json_content }}"
              }
            ]
          }
